---
- name: Update Homebrew
  community.general.homebrew:
    state: latest

- name: Install Homebrew formulae
  community.general.homebrew:
    name: "{{ item }}"
    state: present
    upgrade: true 
  loop: "{{ brew_formulae }}"

- name: Install Homebrew casks
  community.general.homebrew_cask:
    name: "{{ item }}"
    state: present
  loop: "{{ brew_casks }}"

